### ISSUE TITLE
Keyboard navigation inconsistent

### ISSUE THREAD

**Issue by bobbykjack** [rajatkulkarni95/octarine-feedback#1]
I really like the promise of "Keyboard First", but it seems problematic in my experience. For example, if I'm editing in the main panel, then bring up the command bar with Cmd + K, I'm unable to get back to the editing window without resorting to the mouse. Closing it with ESC moves the focus to the bottom-left panel (the file browser?).

Also, when I'm in that state (file browser panel focussed), pressing TAB and/or moving between files with the cursors causes the "?" menu to open (see attachment).
![Screenshot 2024-04-26 at 12 06 16](https://github.com/rajatkulkarni95/octarine-feedback/assets/736352/9e1eab37-82d8-40ab-b19c-7610d44b277c)

**Comment by rajatkulkarni95** [comment]
Hey! Yeah the `CMD + K` close focusing the file tree does seem annoying. Gotta trace back which commit messed it up.

As for the tab thing, in the file tree, everything is based on `up/down` arrows, and tabs in general have been disabled in the app, since they mess with the editor (indenting / unindenting).

But good feedback, I'll take a look at them this weekend!

P.S Are you enjoying the app?

**Comment by bobbykjack** [comment]
I sure am enjoying it, although I'm still in the early stages of trying it out rather than actually using it as my daily driver.

**Comment by rajatkulkarni95** [comment]
@bobbykjack Found a fix for the CMD K thing, will go out in the next release!

https://github.com/rajatkulkarni95/octarine-feedback/assets/57321156/4d87e675-ee74-4de3-8642-67031e7af173

**Comment by rajatkulkarni95** [comment]
Fixed with `v0.14.3`. Out now.
