### ISSUE TITLE
Markdown links requires extra actions to be transformed

### ISSUE THREAD

**Issue by davinkevin** [rajatkulkarni95/octarine-feedback#11]
👋 

When I type a link using `[text](link)` format, I have to `delete` the auto inserted parenthesis to trigger the link transformation. It feels unnatural and unintuive for a user.

See recording for example: 

https://github.com/user-attachments/assets/8e57af4a-413a-462c-aa29-c29b24a9ae26

It would be good to have this trigger automatically when the cursor move out of the parenthesis zone… or just no auto-closing parenthesis so we can explicitly close it and trigger the behavior.

**Comment by rajatkulkarni95** [comment]
Yep, need to improve the link parsing from markdown. The UX around links right now is that you can select any text, and paste the link, and it'll do the markdown parsing in the storage.

Like this -

https://github.com/user-attachments/assets/b80d7da7-a266-4f98-814e-7de0233d8605


Keeping this open, since the app should also do it with the `[text](link)]` format

**Comment by davinkevin** [comment]
Thank you for the tips! I'll do that. I'm so used to low level tools (IDEA, GitHub or GitLab UI…), it's almost natural for me to type this using the `markdown` format directly. 

PS: Thank you for the tool too ♥️

**Comment by davinkevin** [comment]
🥳🥳

Thank you!

**Comment by rajatkulkarni95** [comment]
Out now with [0.17.2](https://octarine.app/changelog/0.17.2)
