### ISSUE TITLE
Minor things 0.18.1

### ISSUE THREAD

**Issue by azureslumbag** [rajatkulkarni95/octarine-feedback#13]
After installing 0.18.1 an image link broke. The image was previously renamed in finder, and seemed to be working, but once I installed the new update, the image wouldn't load. To fix this, I dragged the relevant image into the note again, from attached media.

Not sure if renames follow the file, or I was lucky before. 

Separately, within Octarine, the "What's new in Octarine" page doesn't load in Octarine, after updating, but it links correctly to the website.

**Comment by rajatkulkarni95** [comment]
Weird. I'll see if i can replicate it tomorrow.

Also it seems like Vercel was down for a few minutes that caused the downtime for the changelog page. If you close and open the app, and open the changelog via cmd+k it should load fine

**Comment by rajatkulkarni95** [comment]
> After installing 0.18.1 an image link broke. The image was previously renamed in finder, and seemed to be working, but once I installed the new update, the image wouldn't load. To fix this, I dragged the relevant image into the note again, from attached media.

Ah okay reading this clearly in the morning. So renames made outside of Octarine, do not trigger the `go and fix all the files that have the old name and replace it with the new name` function, since it's harder to understand what was renamed on load, since it gets treated as a `new file` created, and doesn't call the function.

That's why the image rename broke the image, cause the app didn't know something was `renamed`, but rather thought something was `created` (since renaming a file, is essentially a create function in finder as a new path is created)

Hope that makes sense. Closing this issue for now, since it isn't fixable at the moment.
