### ISSUE TITLE
[Bug] files under .folders fail to read data and show the last visited files text in them

### ISSUE THREAD

**Issue by davinkevin** [rajatkulkarni95/octarine-feedback#19]
**Describe the bug**

If I move or jump from a note to another, the title changes but not the content, which can be empty or just the one from the previous note. 

But if I do any modification, I loose the content of the "selected" note completely. 

**To Reproduce**

[Video available following this link](https://link.davinkevin.fr/issue-octarine-text-disapears) (too big to be shared via GitHub unfortunately).

**Expected behavior**

I expect the file switch or moving files to work without causing file content to disappear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 0.19.4

**Additional context**

If you have any question, don't hesitate 😇

**Comment by rajatkulkarni95** [comment]
Weird I've never seen this happen. Can you try creating a new workspace, and try without a .dotfolder?

I'm not sure what could cause note to have it in the storage but not render

**Comment by rajatkulkarni95** [comment]
Here's me trying out similar workflow as yours

https://github.com/user-attachments/assets/dc40b853-a061-48d3-a1b3-9257000e5118

**Comment by rajatkulkarni95** [comment]
Ideally `.folders` should not even be shown, but I'm guessing there's a permissions issue, and the `fs::read` fails, so the editor shows the last available text, since there's no text (full or empty) to replace it with.
https://github.com/user-attachments/assets/52deb19d-ed73-4d62-ad2b-b85c77029eb9


Good catch! Hadn't noticed this. I'll look into a fix for this, or maybe just ignore `.` folders altogether (we already have 2 dot folders and those are reserved - `.attachments` & `.templates`

For the time being, if you don't use the `.done` folder, things should work as expected

**Comment by davinkevin** [comment]
Would be good to support `.` folders, they are very useful especially when you want to hide stuff in finder and keep something at the top of the list. 

But if it's a limitation of the tool, ok, but 😢

**Comment by davinkevin** [comment]
+1 to have everything into `.octarine/tasks` and `.octarine/files`, it makes more sense and is common to a lot of tools (`.idea`, `.gradle`, `.git`…).

Still likes it a lot and thank you for it 😇!

**Comment by rajatkulkarni95** [comment]
Fixed in [0.19.5](https://octarine.app/changelog/0.19.5). Out now.


https://github.com/user-attachments/assets/b6eb7002-b59c-49c6-b628-f436dae8f45c

**Comment by davinkevin** [comment]
Amazing!
